version: "3.9"

services:
#  jdbcDownload:
#    image: curlimages/curl:latest
#    volumes:
#      - ./:/work
#    command: ["curl","-L -o", "postgresql-42.5.4.jar", "https://jdbc.postgresql.org/download/postgresql-42.5.4.jar"]
  db:
    container_name: db
    image: postgres:alpine3.17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
    volumes:
      - ./DeliveryDDL.sql:/docker-entrypoint-initdb.d/DeliveryDDL.sql
  servidor:
    image: payara/server-full:6.2023.4-jdk17
    ports:
      - "8080:8080"
      - "4848:4848"
    volumes:
      - ./postgresql-42.5.4.jar:/opt/payara/appserver/glassfish/domains/domain1/lib/postgresql-42.5.4.jar
      - ./target/deliverytpi.war:/opt/payara/deployments/deliverytpi.war
      - ./post-boot-commands-final.asadmin:/opt/payara/config/post-boot-commands-final.asadmin
    depends_on:
      - db


